config/routes.rb
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU Affero General Public License as
# published by the Free Software Foundation, either version 3 of the
# License, or (at your option) any later version.

# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU Affero General Public License for more details.

# You should have received a copy of the GNU Affero General Public License
# along with this program.  If not, see <https://www.gnu.org/licenses/>.

Rails.application.routes.draw do
  get 'welcome/index'
  devise_for :users
  resources :users, only: [:index, :show, :destroy] do
    member do
      patch :set_role, as: :rerole
    end

    resource :profile, only: [:edit, :update]
    resources :time_records do
      get ':date', action: :new, as: :dated, on: :new
    end
  end

  root to: 'welcome#index'
end

app/models/user.rb
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU Affero General Public License as
# published by the Free Software Foundation, either version 3 of the
# License, or (at your option) any later version.

# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU Affero General Public License for more details.

# You should have received a copy of the GNU Affero General Public License
# along with this program.  If not, see <https://www.gnu.org/licenses/>.

class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable,
         :trackable

  enum role: [:user, :manager, :admin]

  has_one :profile, dependent: :destroy
  has_many :time_records, dependent: :destroy

  after_create do |user|
    user.create_profile! unless user.profile.present?
  end

  def display_name
    profile&.full_name.present? ? profile.full_name : email
  end
end

app/controllers/users_controller.rb
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU Affero General Public License as
# published by the Free Software Foundation, either version 3 of the
# License, or (at your option) any later version.

# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU Affero General Public License for more details.

# You should have received a copy of the GNU Affero General Public License
# along with this program.  If not, see <https://www.gnu.org/licenses/>.

class UsersController < ApplicationController
  before_action :authenticate_user!

  load_and_authorize_resource

  # GET /users
  # GET /users.json
  def index
    @users = @users.includes(:profile).order(:id)
  end

  # GET /users/1
  # GET /users/1.json
  def show
  end

  # PATCH /users/1/set_role
  def set_role
    if @user == current_user
      redirect_back(fallback_location: :root,
        alert: 'You cannot demote yourself, ask another admin to do so' ) and return
    end

    respond_to do |format|
      if @user.update(role: role_param)
        format.html { redirect_to users_url, notice: "#{@user.display_name} is now #{@user.role}" }
        format.json { head :no_content }
      end
    end
  end

  # DELETE /users/1
  # DELETE /users/1.json
  def destroy
    @user.destroy
    respond_to do |format|
      format.html { redirect_to users_url, notice: 'User was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    def role_param
      params.require(:user).require(:role)
    end
end

app/views/users/index.html.erb
<h1>Users</h1>

<table class="table">
  <thead>
    <tr>
      <th>#</th>
      <th>Display name</th>
      <th>Logged in at</th>
      <th>Role</th>
      <th>Actions</th>
    </tr>
  </thead>

  <tbody>
    <% @users.each do |user| %>
      <tr>
        <td><%= user.id %></td>
        <td>
          <%= link_to user, title: user.email do %>
            <% if user&.profile&.full_name.present? %>
              <%= user.profile.full_name %>
            <% else %>
              <%= user.email %>
            <% end %>
          <% end %>
        </td>
        <td><%= user.current_sign_in_at %></td>
        <td>
          <% if can? :set_role, user %>
            <%= simple_form_for user,
              url: rerole_user_path(user),
              method: :patch,
              html: { class: 'form-inline' },
              wrapper: :inline_form do |f| %>

              <%= f.input :role %>
              <%= f.button :submit, 'Update' %>
            <% end %>
          <% else %>
            <%= user.role.humanize %>
          <% end %>
        </td>
        <td>
          <% if can? :destroy, user %>
            <%= link_to '', user, method: :delete,
              data: { confirm: 'Are you sure?' },
              class: 'fas fa-trash text-decoration-none' %>
          <% end %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New User', new_user_registration_path %>

app/views/users/show.html.erb
<h1>
  <%= image_tag Identicon.data_url_for(@user.email, 48) %>
  <%= @user.display_name %>
</h1>

<table class="table time-record-details">
  <tbody>
    <tr>
      <th scope="row">Full name:</th>
      <td><%= @user.profile.full_name.present? ? @user.profile.full_name : '<undefined>' %></td>
    </tr>

    <tr>
      <th scope="row">E-mail:</th>
      <td><%= @user.email %></td>
    </tr>

    <tr>
      <th scope="row">Expected hours:</th>
      <td><%= @user.profile.expected_hours %></td>
    </tr>

    <tr>
      <th scope="row">Logged in at:</th>
      <td><%= @user.current_sign_in_at %></td>
    </tr>
  </tbody>
</table>

<%= link_to 'Edit profile', edit_user_profile_path(@user) %> |
<%= link_to 'Spent hours', user_time_records_path(@user) %> |
<%= link_to 'Back', users_path %>