config/routes.rb
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU Affero General Public License as
# published by the Free Software Foundation, either version 3 of the
# License, or (at your option) any later version.

# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU Affero General Public License for more details.

# You should have received a copy of the GNU Affero General Public License
# along with this program.  If not, see <https://www.gnu.org/licenses/>.

Rails.application.routes.draw do
  get 'welcome/index'
  devise_for :users
  resources :users, only: [:index, :show, :destroy] do
    member do
      patch :set_role, as: :rerole
    end

    resource :profile, only: [:edit, :update]
    resources :time_records do
      get ':date', action: :new, as: :dated, on: :new
    end
  end

  root to: 'welcome#index'
end

app/models/time_record.rb
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU Affero General Public License as
# published by the Free Software Foundation, either version 3 of the
# License, or (at your option) any later version.

# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU Affero General Public License for more details.

# You should have received a copy of the GNU Affero General Public License
# along with this program.  If not, see <https://www.gnu.org/licenses/>.

class TimeRecord < ApplicationRecord
  belongs_to :user

  validates_numericality_of :hours,
    greater_than: 0,
    less_than_or_equal_to: 24

  after_initialize do
    self.date ||= Date.today
  end
end

app/controllers/time_records_controller.rb
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU Affero General Public License as
# published by the Free Software Foundation, either version 3 of the
# License, or (at your option) any later version.

# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU Affero General Public License for more details.

# You should have received a copy of the GNU Affero General Public License
# along with this program.  If not, see <https://www.gnu.org/licenses/>.

class TimeRecordsController < ApplicationController
  before_action :authenticate_user!
  before_action :set_user
  before_action :set_time_record, only: [:show, :edit, :update, :destroy]

  # GET /time_records
  # GET /time_records.json
  def index
    authorize! :list_time_records, @user
    @filter = DateFilter.new date_filter_params

    @time_records = @user.time_records
    @time_records = @time_records.where('date >= ?', @filter.from) if @filter.from.present?
    @time_records = @time_records.where('date <= ?', @filter.to) if @filter.to.present?

    @totals = @time_records.group(:date).sum(:hours).map do |date, hours|
      [date, OpenStruct.new({
        hours: hours,
        sufficient?: (hours >= @user&.profile&.expected_hours.to_i)
      })]
    end.to_h

    @dated_records = @time_records.order({date: :desc, created_at: :desc}).group_by {|r| r.date}
  end

  # GET /time_records/1
  # GET /time_records/1.json
  def show
    authorize! :read, @time_record
  end

  # GET /time_records/new
  def new
    @time_record = TimeRecord.new(user: @user)
    @time_record.date = Date.parse params[:date] rescue Date.today
    authorize! :create, @time_record
  end

  # GET /time_records/1/edit
  def edit
    authorize! :update, @time_record
  end

  # POST /time_records
  # POST /time_records.json
  def create
    @time_record = TimeRecord.new(time_record_params)
    @time_record.user = @user
    authorize! :create, @time_record

    respond_to do |format|
      if @time_record.save
        format.html { redirect_to [@user, @time_record], notice: 'Time record was successfully created.' }
        format.json { render :show, status: :created, location: @time_record }
      else
        format.html { render :new }
        format.json { render json: @time_record.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /time_records/1
  # PATCH/PUT /time_records/1.json
  def update
    authorize! :update, @time_record

    respond_to do |format|
      if @time_record.update(time_record_params)
        format.html { redirect_to [@user, @time_record], notice: 'Time record was successfully updated.' }
        format.json { render :show, status: :ok, location: @time_record }
      else
        format.html { render :edit }
        format.json { render json: @time_record.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /time_records/1
  # DELETE /time_records/1.json
  def destroy
    authorize! :destroy, @time_record

    @time_record.destroy
    respond_to do |format|
      format.html { redirect_to user_time_records_url(@user), notice: 'Time record was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_user
      @user = User.find(params[:user_id])
    end

    def set_time_record
      @time_record = @user.time_records.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def time_record_params
      params.require(:time_record).permit(:date, :hours, :description)
    end

    def date_filter_params
      params.fetch(:date_filter, {}).permit(:from, :to)
    end
end

app/views/time_records/_form.html.erb
<%= simple_form_for([@user, @time_record],
  html: { class: 'form-horizontal' },
  wrapper: :horizontal_form) do |f| %>

  <%= f.error_notification %>
  <%= f.error_notification message: f.object.errors[:base].to_sentence if f.object.errors[:base].present? %>

  <div class="form-inputs">
    <%= f.input :date, html5: true, wrapper: :horizontal_form, input_html: { step: 1 } %>
    <%= f.input :hours, input_html: { step: 0.1, min: 0, lang: :en } %>
    <%= f.input :description %>
  </div>

  <div class="form-actions">
    <%= f.button :submit %>
  </div>
<% end %>

app/views/time_records/edit.html.erb
<h1>Editing Time Record</h1>

<%= render 'form', time_record: @time_record %>

<%= link_to 'Show', [@user, @time_record] %> |
<%= link_to 'Back', user_time_records_path(@user) %>

app/views/time_records/index.html.erb
<h1>Time Records for <%= link_to @user.display_name, @user %></h1>

<div class="d-flex flex-row justify-content-between mb-3">
  <%= simple_form_for @filter,
    url: user_time_records_path(@user),
    method: :get,
    html: { class: 'form-inline' },
    wrapper: :inline_form do |f| %>

    <%= f.label 'Filter records', class: 'mx-1' %>

    <%= f.label :from, 'from', class: 'mx-1' %>
    <%= f.input :from, as: :date, html5: true,
      wrapper: :inline_form,
      label: false,
      input_html: { step: 1, class: 'mx-1' } %>

    <%= f.label :to, 'to', class: 'mx-1' %>
    <%= f.input :to, as: :date, html5: true,
      wrapper: :inline_form,
      label: false,
      input_html: { step: 1, class: 'mx-1' } %>

    <%= f.button :submit, 'Filter' %>
  <% end %>

  <%= link_to_if can?(:create, TimeRecord), 'New Time Record', new_user_time_record_path(@user),
      class: 'nav-link' %>
</div>

<table class="table">
  <thead>
    <tr>
      <th>Hours</th>
      <th>Description</th>
      <th>Actions</th>
    </tr>
  </thead>

  <tbody>
    <% @dated_records.each do |date, time_records| %>
      <tr class="bg-<%= (@totals[date].sufficient?) ? 'success' : 'danger' %> text-light time-total">
        <th scope="row"><%= @totals[date].hours %></th>
        <td>
          <strong>Total at</strong>
          <%= date %>
        </td>
        <td>
          <%= link_to_if can?(:create, TimeRecord), '', dated_new_user_time_record_path(@user, date),
              title: "New record at #{date}",
              class: 'fas fa-plus text-decoration-none text-light' %>
        </td>
      </tr>
      <% time_records.each do |time_record| %>
        <tr class="time-record">
          <td><%= time_record.hours %></td>
          <td>
            <% if time_record.description.present? %>
              <%= truncate time_record.description.lines.first.strip, length: 80, separator: /\s/ %>
            <% else %>
              <em>No description</em>
            <% end %>
            <%= link_to '(more)', [@user, time_record] %>
          </td>
          <td>
            <%= link_to_if can?(:destroy, time_record), '', edit_user_time_record_path(@user, time_record),
              title: 'Edit',
              class: 'fas fa-edit text-decoration-none' %>
            <%= link_to_if can?(:destroy, time_record), '', [@user, time_record],
              title: 'Destroy',
              method: :delete,
              data: { confirm: 'Are you sure?' },
              class: 'fas fa-trash text-decoration-none' %>
          </td>
        </tr>
      <% end %>
    <% end %>
  </tbody>
</table>

app/views/time_records/new.html.erb
<h1>New Time Record</h1>

<%= render 'form', time_record: @time_record %>

<%= link_to 'Back', user_time_records_path(@user) %>

app/views/time_records/show.html.erb
<table class="table time-record-details">
  <tbody>
    <tr>
      <th scope="row">User:</th>
      <td><%= link_to @time_record.user.display_name, @time_record.user %></td>
    </tr>

    <tr>
      <th scope="row">Date:</th>
      <td><%= @time_record.date %></td>
    </tr>

    <tr>
      <th scope="row">Hours:</th>
      <td><%= @time_record.hours %></td>
    </tr>

    <tr>
      <th scope="row">Description:</th>
      <td><%= simple_format @time_record.description %></td>
    </tr>
  </tbody>
</table>

<%= link_to 'Edit', edit_user_time_record_path(@user, @time_record) %> |
<%= link_to 'Back', user_time_records_path(@user) %>